// flow-typed signature: 3e3eb4695fbd427f746cf978a01379d7
// flow-typed version: <<STUB>>/epub.js_v^0.2.15/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'epub.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'epub.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'epub.js/build/epub' {
  declare module.exports: any;
}

declare module 'epub.js/build/epub.min' {
  declare module.exports: any;
}

declare module 'epub.js/build/hooks' {
  declare module.exports: any;
}

declare module 'epub.js/build/hooks.min' {
  declare module.exports: any;
}

declare module 'epub.js/build/libs/localforage.min' {
  declare module.exports: any;
}

declare module 'epub.js/build/libs/zip.min' {
  declare module.exports: any;
}

declare module 'epub.js/build/reader' {
  declare module.exports: any;
}

declare module 'epub.js/build/reader.min' {
  declare module.exports: any;
}

declare module 'epub.js/examples/wgxpath.install' {
  declare module.exports: any;
}

declare module 'epub.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/default/endnotes' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/default/mathml' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/default/smartimages' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/default/transculsions' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/annotate' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/example' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/highlight' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/hypothesis' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/music' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/pageturns' {
  declare module.exports: any;
}

declare module 'epub.js/hooks/extensions/wgxpath' {
  declare module.exports: any;
}

declare module 'epub.js/libs/jszip/jszip' {
  declare module.exports: any;
}

declare module 'epub.js/libs/jszip/jszip.min' {
  declare module.exports: any;
}

declare module 'epub.js/libs/mime-types/mime-types' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/bookmarks_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/controls_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/meta_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/notes_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/reader_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/settings_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/sidebar_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/controllers/toc_controller' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/old/app' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/old/utils' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/plugins/hypothesis' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/plugins/search' {
  declare module.exports: any;
}

declare module 'epub.js/reader_src/reader' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/epub.min' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/hooks.min' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/hooks/extensions/highlight' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/libs/jquery.min' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/libs/screenfull' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/libs/screenfull.min' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/libs/zip.min' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/plugins/hypothesis' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/plugins/search' {
  declare module.exports: any;
}

declare module 'epub.js/reader/js/reader.min' {
  declare module.exports: any;
}

declare module 'epub.js/server' {
  declare module.exports: any;
}

declare module 'epub.js/src/base' {
  declare module.exports: any;
}

declare module 'epub.js/src/book' {
  declare module.exports: any;
}

declare module 'epub.js/src/chapter' {
  declare module.exports: any;
}

declare module 'epub.js/src/core' {
  declare module.exports: any;
}

declare module 'epub.js/src/epubcfi' {
  declare module.exports: any;
}

declare module 'epub.js/src/events' {
  declare module.exports: any;
}

declare module 'epub.js/src/hooks' {
  declare module.exports: any;
}

declare module 'epub.js/src/layout' {
  declare module.exports: any;
}

declare module 'epub.js/src/locations' {
  declare module.exports: any;
}

declare module 'epub.js/src/pagination' {
  declare module.exports: any;
}

declare module 'epub.js/src/parser' {
  declare module.exports: any;
}

declare module 'epub.js/src/render_iframe' {
  declare module.exports: any;
}

declare module 'epub.js/src/renderer' {
  declare module.exports: any;
}

declare module 'epub.js/src/replace' {
  declare module.exports: any;
}

declare module 'epub.js/src/shims' {
  declare module.exports: any;
}

declare module 'epub.js/src/storage' {
  declare module.exports: any;
}

declare module 'epub.js/src/unarchiver' {
  declare module.exports: any;
}

declare module 'epub.js/tests/chapter' {
  declare module.exports: any;
}

declare module 'epub.js/tests/core' {
  declare module.exports: any;
}

declare module 'epub.js/tests/epubcfi' {
  declare module.exports: any;
}

declare module 'epub.js/tests/pagination' {
  declare module.exports: any;
}

declare module 'epub.js/tests/qunit/qunit' {
  declare module.exports: any;
}

declare module 'epub.js/tests/render' {
  declare module.exports: any;
}

declare module 'epub.js/tests/unarchiver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'epub.js/build/epub.js' {
  declare module.exports: $Exports<'epub.js/build/epub'>;
}
declare module 'epub.js/build/epub.min.js' {
  declare module.exports: $Exports<'epub.js/build/epub.min'>;
}
declare module 'epub.js/build/hooks.js' {
  declare module.exports: $Exports<'epub.js/build/hooks'>;
}
declare module 'epub.js/build/hooks.min.js' {
  declare module.exports: $Exports<'epub.js/build/hooks.min'>;
}
declare module 'epub.js/build/libs/localforage.min.js' {
  declare module.exports: $Exports<'epub.js/build/libs/localforage.min'>;
}
declare module 'epub.js/build/libs/zip.min.js' {
  declare module.exports: $Exports<'epub.js/build/libs/zip.min'>;
}
declare module 'epub.js/build/reader.js' {
  declare module.exports: $Exports<'epub.js/build/reader'>;
}
declare module 'epub.js/build/reader.min.js' {
  declare module.exports: $Exports<'epub.js/build/reader.min'>;
}
declare module 'epub.js/examples/wgxpath.install.js' {
  declare module.exports: $Exports<'epub.js/examples/wgxpath.install'>;
}
declare module 'epub.js/Gruntfile.js' {
  declare module.exports: $Exports<'epub.js/Gruntfile'>;
}
declare module 'epub.js/hooks/default/endnotes.js' {
  declare module.exports: $Exports<'epub.js/hooks/default/endnotes'>;
}
declare module 'epub.js/hooks/default/mathml.js' {
  declare module.exports: $Exports<'epub.js/hooks/default/mathml'>;
}
declare module 'epub.js/hooks/default/smartimages.js' {
  declare module.exports: $Exports<'epub.js/hooks/default/smartimages'>;
}
declare module 'epub.js/hooks/default/transculsions.js' {
  declare module.exports: $Exports<'epub.js/hooks/default/transculsions'>;
}
declare module 'epub.js/hooks/extensions/annotate.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/annotate'>;
}
declare module 'epub.js/hooks/extensions/example.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/example'>;
}
declare module 'epub.js/hooks/extensions/highlight.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/highlight'>;
}
declare module 'epub.js/hooks/extensions/hypothesis.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/hypothesis'>;
}
declare module 'epub.js/hooks/extensions/music.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/music'>;
}
declare module 'epub.js/hooks/extensions/pageturns.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/pageturns'>;
}
declare module 'epub.js/hooks/extensions/wgxpath.js' {
  declare module.exports: $Exports<'epub.js/hooks/extensions/wgxpath'>;
}
declare module 'epub.js/libs/jszip/jszip.js' {
  declare module.exports: $Exports<'epub.js/libs/jszip/jszip'>;
}
declare module 'epub.js/libs/jszip/jszip.min.js' {
  declare module.exports: $Exports<'epub.js/libs/jszip/jszip.min'>;
}
declare module 'epub.js/libs/mime-types/mime-types.js' {
  declare module.exports: $Exports<'epub.js/libs/mime-types/mime-types'>;
}
declare module 'epub.js/reader_src/controllers/bookmarks_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/bookmarks_controller'>;
}
declare module 'epub.js/reader_src/controllers/controls_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/controls_controller'>;
}
declare module 'epub.js/reader_src/controllers/meta_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/meta_controller'>;
}
declare module 'epub.js/reader_src/controllers/notes_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/notes_controller'>;
}
declare module 'epub.js/reader_src/controllers/reader_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/reader_controller'>;
}
declare module 'epub.js/reader_src/controllers/settings_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/settings_controller'>;
}
declare module 'epub.js/reader_src/controllers/sidebar_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/sidebar_controller'>;
}
declare module 'epub.js/reader_src/controllers/toc_controller.js' {
  declare module.exports: $Exports<'epub.js/reader_src/controllers/toc_controller'>;
}
declare module 'epub.js/reader_src/old/app.js' {
  declare module.exports: $Exports<'epub.js/reader_src/old/app'>;
}
declare module 'epub.js/reader_src/old/utils.js' {
  declare module.exports: $Exports<'epub.js/reader_src/old/utils'>;
}
declare module 'epub.js/reader_src/plugins/hypothesis.js' {
  declare module.exports: $Exports<'epub.js/reader_src/plugins/hypothesis'>;
}
declare module 'epub.js/reader_src/plugins/search.js' {
  declare module.exports: $Exports<'epub.js/reader_src/plugins/search'>;
}
declare module 'epub.js/reader_src/reader.js' {
  declare module.exports: $Exports<'epub.js/reader_src/reader'>;
}
declare module 'epub.js/reader/js/epub.min.js' {
  declare module.exports: $Exports<'epub.js/reader/js/epub.min'>;
}
declare module 'epub.js/reader/js/hooks.min.js' {
  declare module.exports: $Exports<'epub.js/reader/js/hooks.min'>;
}
declare module 'epub.js/reader/js/hooks/extensions/highlight.js' {
  declare module.exports: $Exports<'epub.js/reader/js/hooks/extensions/highlight'>;
}
declare module 'epub.js/reader/js/libs/jquery.min.js' {
  declare module.exports: $Exports<'epub.js/reader/js/libs/jquery.min'>;
}
declare module 'epub.js/reader/js/libs/screenfull.js' {
  declare module.exports: $Exports<'epub.js/reader/js/libs/screenfull'>;
}
declare module 'epub.js/reader/js/libs/screenfull.min.js' {
  declare module.exports: $Exports<'epub.js/reader/js/libs/screenfull.min'>;
}
declare module 'epub.js/reader/js/libs/zip.min.js' {
  declare module.exports: $Exports<'epub.js/reader/js/libs/zip.min'>;
}
declare module 'epub.js/reader/js/plugins/hypothesis.js' {
  declare module.exports: $Exports<'epub.js/reader/js/plugins/hypothesis'>;
}
declare module 'epub.js/reader/js/plugins/search.js' {
  declare module.exports: $Exports<'epub.js/reader/js/plugins/search'>;
}
declare module 'epub.js/reader/js/reader.min.js' {
  declare module.exports: $Exports<'epub.js/reader/js/reader.min'>;
}
declare module 'epub.js/server.js' {
  declare module.exports: $Exports<'epub.js/server'>;
}
declare module 'epub.js/src/base.js' {
  declare module.exports: $Exports<'epub.js/src/base'>;
}
declare module 'epub.js/src/book.js' {
  declare module.exports: $Exports<'epub.js/src/book'>;
}
declare module 'epub.js/src/chapter.js' {
  declare module.exports: $Exports<'epub.js/src/chapter'>;
}
declare module 'epub.js/src/core.js' {
  declare module.exports: $Exports<'epub.js/src/core'>;
}
declare module 'epub.js/src/epubcfi.js' {
  declare module.exports: $Exports<'epub.js/src/epubcfi'>;
}
declare module 'epub.js/src/events.js' {
  declare module.exports: $Exports<'epub.js/src/events'>;
}
declare module 'epub.js/src/hooks.js' {
  declare module.exports: $Exports<'epub.js/src/hooks'>;
}
declare module 'epub.js/src/layout.js' {
  declare module.exports: $Exports<'epub.js/src/layout'>;
}
declare module 'epub.js/src/locations.js' {
  declare module.exports: $Exports<'epub.js/src/locations'>;
}
declare module 'epub.js/src/pagination.js' {
  declare module.exports: $Exports<'epub.js/src/pagination'>;
}
declare module 'epub.js/src/parser.js' {
  declare module.exports: $Exports<'epub.js/src/parser'>;
}
declare module 'epub.js/src/render_iframe.js' {
  declare module.exports: $Exports<'epub.js/src/render_iframe'>;
}
declare module 'epub.js/src/renderer.js' {
  declare module.exports: $Exports<'epub.js/src/renderer'>;
}
declare module 'epub.js/src/replace.js' {
  declare module.exports: $Exports<'epub.js/src/replace'>;
}
declare module 'epub.js/src/shims.js' {
  declare module.exports: $Exports<'epub.js/src/shims'>;
}
declare module 'epub.js/src/storage.js' {
  declare module.exports: $Exports<'epub.js/src/storage'>;
}
declare module 'epub.js/src/unarchiver.js' {
  declare module.exports: $Exports<'epub.js/src/unarchiver'>;
}
declare module 'epub.js/tests/chapter.js' {
  declare module.exports: $Exports<'epub.js/tests/chapter'>;
}
declare module 'epub.js/tests/core.js' {
  declare module.exports: $Exports<'epub.js/tests/core'>;
}
declare module 'epub.js/tests/epubcfi.js' {
  declare module.exports: $Exports<'epub.js/tests/epubcfi'>;
}
declare module 'epub.js/tests/pagination.js' {
  declare module.exports: $Exports<'epub.js/tests/pagination'>;
}
declare module 'epub.js/tests/qunit/qunit.js' {
  declare module.exports: $Exports<'epub.js/tests/qunit/qunit'>;
}
declare module 'epub.js/tests/render.js' {
  declare module.exports: $Exports<'epub.js/tests/render'>;
}
declare module 'epub.js/tests/unarchiver.js' {
  declare module.exports: $Exports<'epub.js/tests/unarchiver'>;
}
