// flow-typed signature: 1a31c670e278bebccea7d867dec272c0
// flow-typed version: <<STUB>>/rxdb_v^3.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rxdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rxdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rxdb/config/gulpfile' {
  declare module.exports: any;
}

declare module 'rxdb/config/karma.conf' {
  declare module.exports: any;
}

declare module 'rxdb/config/rollup.config' {
  declare module.exports: any;
}

declare module 'rxdb/config/webpack.config' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/Crypter' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/DataMigrator' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/DocCache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/KeyCompressor' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/LeaderElector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/PouchDB' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxBroadcastChannel' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxChangeEvent' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxCollection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxDatabase' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxDocument' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxQuery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/RxSchema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/Socket' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/util' {
  declare module.exports: any;
}

declare module 'rxdb/dist/rxdb.browserify' {
  declare module.exports: any;
}

declare module 'rxdb/dist/rxdb.browserify.min' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/index' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/index' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage-core' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/taskqueue' {
  declare module.exports: any;
}

declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/utils' {
  declare module.exports: any;
}

declare module 'rxdb/src/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/src/Crypter' {
  declare module.exports: any;
}

declare module 'rxdb/src/DataMigrator' {
  declare module.exports: any;
}

declare module 'rxdb/src/DocCache' {
  declare module.exports: any;
}

declare module 'rxdb/src/index' {
  declare module.exports: any;
}

declare module 'rxdb/src/KeyCompressor' {
  declare module.exports: any;
}

declare module 'rxdb/src/LeaderElector' {
  declare module.exports: any;
}

declare module 'rxdb/src/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/src/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/src/PouchDB' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxBroadcastChannel' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxChangeEvent' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxCollection' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxDatabase' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxDocument' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxQuery' {
  declare module.exports: any;
}

declare module 'rxdb/src/RxSchema' {
  declare module.exports: any;
}

declare module 'rxdb/src/Socket' {
  declare module.exports: any;
}

declare module 'rxdb/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rxdb/config/gulpfile.js' {
  declare module.exports: $Exports<'rxdb/config/gulpfile'>;
}
declare module 'rxdb/config/karma.conf.js' {
  declare module.exports: $Exports<'rxdb/config/karma.conf'>;
}
declare module 'rxdb/config/rollup.config.js' {
  declare module.exports: $Exports<'rxdb/config/rollup.config'>;
}
declare module 'rxdb/config/webpack.config.js' {
  declare module.exports: $Exports<'rxdb/config/webpack.config'>;
}
declare module 'rxdb/dist/lib/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/browserify.index'>;
}
declare module 'rxdb/dist/lib/Crypter.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/Crypter'>;
}
declare module 'rxdb/dist/lib/DataMigrator.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/DataMigrator'>;
}
declare module 'rxdb/dist/lib/DocCache.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/DocCache'>;
}
declare module 'rxdb/dist/lib/index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/index'>;
}
declare module 'rxdb/dist/lib/KeyCompressor.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/KeyCompressor'>;
}
declare module 'rxdb/dist/lib/LeaderElector.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/LeaderElector'>;
}
declare module 'rxdb/dist/lib/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/mquery/mquery_utils'>;
}
declare module 'rxdb/dist/lib/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/mquery/mquery'>;
}
declare module 'rxdb/dist/lib/PouchDB.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/PouchDB'>;
}
declare module 'rxdb/dist/lib/RxBroadcastChannel.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxBroadcastChannel'>;
}
declare module 'rxdb/dist/lib/RxChangeEvent.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxChangeEvent'>;
}
declare module 'rxdb/dist/lib/RxCollection.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxCollection'>;
}
declare module 'rxdb/dist/lib/RxDatabase.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxDatabase'>;
}
declare module 'rxdb/dist/lib/RxDocument.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxDocument'>;
}
declare module 'rxdb/dist/lib/RxQuery.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxQuery'>;
}
declare module 'rxdb/dist/lib/RxSchema.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/RxSchema'>;
}
declare module 'rxdb/dist/lib/Socket.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/Socket'>;
}
declare module 'rxdb/dist/lib/util.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/util'>;
}
declare module 'rxdb/dist/rxdb.browserify.js' {
  declare module.exports: $Exports<'rxdb/dist/rxdb.browserify'>;
}
declare module 'rxdb/dist/rxdb.browserify.min.js' {
  declare module.exports: $Exports<'rxdb/dist/rxdb.browserify.min'>;
}
declare module 'rxdb/plugins/adapter-localstorage/index.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/index'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/index.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/index'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage-core.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage-core'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/localstorage'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/taskqueue.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/taskqueue'>;
}
declare module 'rxdb/plugins/adapter-localstorage/localstorage-down/lib/utils.js' {
  declare module.exports: $Exports<'rxdb/plugins/adapter-localstorage/localstorage-down/lib/utils'>;
}
declare module 'rxdb/src/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/src/browserify.index'>;
}
declare module 'rxdb/src/Crypter.js' {
  declare module.exports: $Exports<'rxdb/src/Crypter'>;
}
declare module 'rxdb/src/DataMigrator.js' {
  declare module.exports: $Exports<'rxdb/src/DataMigrator'>;
}
declare module 'rxdb/src/DocCache.js' {
  declare module.exports: $Exports<'rxdb/src/DocCache'>;
}
declare module 'rxdb/src/index.js' {
  declare module.exports: $Exports<'rxdb/src/index'>;
}
declare module 'rxdb/src/KeyCompressor.js' {
  declare module.exports: $Exports<'rxdb/src/KeyCompressor'>;
}
declare module 'rxdb/src/LeaderElector.js' {
  declare module.exports: $Exports<'rxdb/src/LeaderElector'>;
}
declare module 'rxdb/src/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/src/mquery/mquery_utils'>;
}
declare module 'rxdb/src/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/src/mquery/mquery'>;
}
declare module 'rxdb/src/PouchDB.js' {
  declare module.exports: $Exports<'rxdb/src/PouchDB'>;
}
declare module 'rxdb/src/RxBroadcastChannel.js' {
  declare module.exports: $Exports<'rxdb/src/RxBroadcastChannel'>;
}
declare module 'rxdb/src/RxChangeEvent.js' {
  declare module.exports: $Exports<'rxdb/src/RxChangeEvent'>;
}
declare module 'rxdb/src/RxCollection.js' {
  declare module.exports: $Exports<'rxdb/src/RxCollection'>;
}
declare module 'rxdb/src/RxDatabase.js' {
  declare module.exports: $Exports<'rxdb/src/RxDatabase'>;
}
declare module 'rxdb/src/RxDocument.js' {
  declare module.exports: $Exports<'rxdb/src/RxDocument'>;
}
declare module 'rxdb/src/RxQuery.js' {
  declare module.exports: $Exports<'rxdb/src/RxQuery'>;
}
declare module 'rxdb/src/RxSchema.js' {
  declare module.exports: $Exports<'rxdb/src/RxSchema'>;
}
declare module 'rxdb/src/Socket.js' {
  declare module.exports: $Exports<'rxdb/src/Socket'>;
}
declare module 'rxdb/src/util.js' {
  declare module.exports: $Exports<'rxdb/src/util'>;
}
